"""Google-Colab GPU training pipeline for the experimental windowed 1D-CNN blind decoder.

PyTorch (matches the project's decoder stack). Trains the paper-style per-bit
windowed CNN on DIV2K where EVERY training sample is generated by the **actual,
existing project encoder** (`src.watermark.embed.embed` + the authoritative
`bit_window_singular_values` mapping), so the network learns the exact signal
the production embedder produces. Labels are the physical bits actually
embedded — never derived independently.

Notebook: ``training/colab_windowed_cnn_training.ipynb`` (thin wrapper around
this file). Run everything at once::

    python colab_train_decoder.py --project-root /content/deep-watermarking --all

or stage-by-stage from the notebook cells.

Key decisions (documented in docs/windowed_cnn.md and the notebook):

* **Frozen embedder, untouched.** This pipeline only *calls* the existing
  ``embed()``; it never re-implements or modifies the encoding mathematics.
* **Payloads from the real codec.** Training payloads come from
  ``id_registry.encode_id_bits(id)`` (interleaving + balanced XOR mask), so the
  learned bits ARE the physical bits the ownership/registry flow embeds.
* **One authoritative mapping.** ``bit_window_singular_values`` is shared by
  cache generation and live inference.
* **Split 700/100/100.** Released DIV2K has 900 images (train 800, valid 100);
  the master target "800 train / 100 val / 100 test" needs 1000, so test = the
  official valid set (IDs 0801-0900, same as the local project's test split),
  validation = the official-train tail (0701-0800), train = 0001-0700.
  Image-level separation is preserved (a file lives in exactly one split).
* **Cached windows.** Embedding-to-windows is a separate stage (npz cache with a
  config hash; rebuilt automatically when the config changes), so GPU training
  reads arrays instead of re-running the embedder.

Artifacts written to ``<out>/windowed_cnn``:
    windowed_cnn_best.pt / windowed_cnn_last.pt   (self-describing checkpoints)
    normalization.npz   (the feature transform the decoder expects)
    decoder_config.json (WindowedCNNConfig + bit_length + image_size)
    training_config.json
    training_history.csv
    dataset_split.json
    metrics.json
    windowed_cnn_model_package.zip  (self-contained download bundle)
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import random
import sys
import time
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import torch
from torch import nn

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

try:
    import kagglehub
except Exception:  # noqa: BLE001 - optional dependency, handled in download_div2k
    kagglehub = None  # type: ignore[assignment]

import cv2
import yaml

from src.models.windowed_cnn import (
    WINDOW_DEFAULT,
    WindowedCNNConfig,
    WindowedCNNExtractor,
    bit_window_singular_values,
    load_windowed_checkpoint,
    luminance_ll_singular_values,
    save_windowed_checkpoint,
)
from src.watermark import id_registry
from src.watermark.embed import EmbedConfig, embed

# Kaggle dataset that mirrors the official DIV2K HR images (same IDs/layout).
KAGGLE_DATASET = "soumikrakshit/div2k-high-resolution-images"

# Master-prompt default config (paper reference) - overridable on the CLI.
EPOCHS = 50
BATCH_SIZE = 64
BIT_LENGTH = 64
WINDOW_SIZE = WINDOW_DEFAULT  # 15
IMAGE_SIZE = 256
ALPHA = 0.02
SEED = 20260906
PATIENCE = 10
LR = 1e-3

KAGGLE_LAYOUTS = (
    ("DIV2K_train_HR", "DIV2K_valid_HR"),
    ("train", "valid"),
)


class ColabPipelineError(RuntimeError):
    """User-correctable problem in the Colab pipeline."""


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------


def check_environment(require_gpu: bool = False) -> dict:
    """Return runtime facts; optionally hard-fail when CUDA is unavailable."""
    info = {
        "python": sys.version.split()[0],
        "torch": torch.__version__,
        "cuda_available": bool(torch.cuda.is_available()),
        "gpu_count": int(torch.cuda.device_count()) if torch.cuda.is_available() else 0,
        "gpu_name": torch.cuda.get_device_name(0)
        if torch.cuda.is_available() and torch.cuda.device_count() > 0
        else None,
        "numpy": np.__version__,
    }
    if require_gpu and not info["cuda_available"]:
        raise ColabPipelineError(
            "No CUDA GPU detected. Colab: Runtime -> Change runtime type -> T4 GPU "
            "(or A100). The pipeline trains without one, but is much slower."
        )
    return info


def _seed_everything(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class PipelineConfig:
    project_root: str
    bit_length: int = BIT_LENGTH
    window_size: int = WINDOW_SIZE
    image_size: int = IMAGE_SIZE
    alpha: float = ALPHA
    seed: int = SEED
    epochs: int = EPOCHS
    batch_size: int = BATCH_SIZE
    lr: float = LR
    patience: int = PATIENCE
    num_workers: int = 2
    out_dir: str = "content/out"
    split_mode: str = "700"  # "700" | "800" (see module docstring)
    cache_dir: str = "content/windows"
    train_images: int | None = None  # cap for smoke runs
    val_images: int | None = None
    test_images: int | None = None
    processed_root: str = "data/processed/div2k_256"
    train_split: str = "train"
    validation_split: str = "validation"
    test_split: str = "test"

    def embed_config(self) -> EmbedConfig:
        return EmbedConfig(
            wavelet="haar",
            subband="LL",
            mode="symmetric",
            alpha=self.alpha,
            bit_length=self.bit_length,
            start_sv_index=0,
        )

    def model_config(self) -> WindowedCNNConfig:
        return WindowedCNNConfig(
            bit_length=self.bit_length,
            window_size=self.window_size,
            wavelet="haar",
            mode="symmetric",
            subband="LL",
            image_size=self.image_size,
        )

    def resolved(self) -> PipelineConfig:
        (Path(self.project_root) / "data").resolve()
        return PipelineConfig(
            project_root=self.project_root,
            bit_length=self.bit_length,
            window_size=self.window_size,
            image_size=self.image_size,
            alpha=self.alpha,
            seed=self.seed,
            epochs=self.epochs,
            batch_size=self.batch_size,
            lr=self.lr,
            patience=self.patience,
            num_workers=self.num_workers,
            out_dir=str(Path(self.out_dir).resolve()),
            split_mode=self.split_mode,
            cache_dir=str(Path(self.cache_dir).resolve()),
            train_images=self.train_images,
            val_images=self.val_images,
            test_images=self.test_images,
            processed_root=str(Path(self.project_root, self.processed_root).resolve()),
            train_split=self.train_split,
            validation_split=self.validation_split,
            test_split=self.test_split,
        )

    def config_hash(self) -> str:
        raw = (self.bit_length, self.window_size, self.image_size, self.alpha, self.split_mode)
        return hashlib.sha256(json.dumps(raw, sort_keys=True).encode()).hexdigest()[:12]


def load_pipeline_config(project_root: str, overrides: dict | None = None) -> PipelineConfig:
    path = Path(project_root) / "configs" / "windowed_cnn.yaml"
    base = PipelineConfig(project_root=str(project_root))
    if path.is_file():
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))["windowed_cnn"]
        base = PipelineConfig(
            project_root=str(project_root),
            bit_length=int(raw.get("payload", {}).get("bit_length", BIT_LENGTH)),
            window_size=int(raw.get("model", {}).get("window_size", WINDOW_SIZE)),
            image_size=int(raw.get("model", {}).get("image_size", IMAGE_SIZE)),
            alpha=float(raw.get("embed", {}).get("alpha", ALPHA)),
            seed=int(raw.get("train", {}).get("seed", SEED)),
            epochs=int(raw.get("train", {}).get("epochs", EPOCHS)),
            batch_size=int(raw.get("train", {}).get("batch_size", BATCH_SIZE)),
            lr=float(raw.get("train", {}).get("lr", LR)),
            patience=int(raw.get("train", {}).get("early_stop_patience", PATIENCE)),
            num_workers=int(raw.get("train", {}).get("num_workers", 2)),
            split_mode=raw.get("data", {}).get("split_mode", "700"),
            processed_root=raw.get("data", {}).get("processed_root", "data/processed/div2k_256"),
            train_split=raw.get("data", {}).get("train_split", "train"),
            validation_split=raw.get("data", {}).get("validation_split", "validation"),
            test_split=raw.get("data", {}).get("test_split", "test"),
        )
    for key, value in (overrides or {}).items():
        if value is not None and hasattr(base, key):
            base = PipelineConfig(**{**asdict(base), key: value})
    return base


# ---------------------------------------------------------------------------
# DIV2K
# ---------------------------------------------------------------------------


def _png_id(path: Path) -> int:
    try:
        return int(path.stem)
    except ValueError:
        # kagglehub vendors sometimes prefix the folder name - take the last int.
        match = __import__("re").search(r"(\d+)$", path.stem)
        if not match:
            raise ColabPipelineError(f"unexpected DIV2K filename: {path.name}")
        return int(match.group(1))


def find_image_dirs(source: Path) -> tuple[Path, Path]:
    for train_name, valid_name in KAGGLE_LAYOUTS:
        train_dir, valid_dir = source / train_name, source / valid_name
        if train_dir.is_dir() and valid_dir.is_dir():
            return train_dir, valid_dir
    raise ColabPipelineError(
        f"could not find DIV2K train/valid folders under {source}. Expected one of "
        f"{['/'.join(p) for p in KAGGLE_LAYOUTS]}"
    )


def discover_div2k_pngs(source: Path) -> tuple[list[Path], list[Path]]:
    """Layout-agnostic DIV2K discovery.

    Recursively scans ``source`` (any nesting depth), extracts any still-zipped
    ``*.zip``/``*.archive`` files it finds (kagglehub mirrors often ship the
    official archives zipped one level deeper), and groups the 900 PNGs by their
    official image ID: 0001-0800 -> train, 0801-0900 -> valid. Folder names are
    irrelevant - the ID is authoritative, so ``DIV2K_train_HR``,
    ``train``/``valid``, flat or nested layouts all work identically.
    """
    source = Path(source)
    for archive in list(source.rglob("*")):
        if (
            archive.is_file()
            and archive.suffix.lower() in (".zip", ".archive")
        ):
            try:
                with zipfile.ZipFile(archive) as zf:
                    zf.extractall(archive.parent)
                archive.unlink(missing_ok=True)
                print(f"[div2k] extracted nested archive: {archive.name}")
            except zipfile.BadZipFile:
                continue

    by_id: dict[int, Path] = {}
    for p in source.rglob("*.png"):
        if not p.is_file():
            continue
        try:
            by_id.setdefault(_png_id(p), p)
        except ColabPipelineError:
            continue
    missing = [i for i in range(1, 901) if i not in by_id]
    if missing:
        raise ColabPipelineError(
            f"official DIV2K image set incomplete: {len(missing)} of 900 images "
            f"missing (first:{missing[:10]}). The source layout or mirror differs "
            "- use SOURCE='official' with the official archives, or SOURCE='fake'."
        )
    train = [by_id[i] for i in range(1, 801)]
    valid = [by_id[i] for i in range(801, 901)]
    print(
        f"[div2k] discovered {len(train) + len(valid)} images under {source} "
        f"(train={len(train)} valid={len(valid)})"
    )
    return train, valid


def download_div2k(
    config: PipelineConfig,
    *,
    use_kagglehub: bool = True,
    fake: bool = False,
) -> tuple[list[Path], list[Path]]:
    """Return ``(train_pngs, valid_pngs)`` - the official 800 + 100 HR files.

    ``fake=True`` (dev/smoke): builds a throwaway DIV2K-shaped tree of small
    synthetic 256x256 PNGs in a temp dir so the whole pipeline can be verified
    on a CPU laptop without a real download. Returns file lists in both modes.
    """
    if fake:
        import tempfile

        tmp = Path(tempfile.mkdtemp(prefix="div2k_fake_")) / "div2k_hr"
        train_dir, valid_dir = tmp / "DIV2K_train_HR", tmp / "DIV2K_valid_HR"
        train_dir.mkdir(parents=True), valid_dir.mkdir(parents=True)
        rng = np.random.default_rng(1234)
        base = (rng.random((256, 256, 3)) * 255).astype(np.uint8)
        total = 900
        for i in range(1, total + 1):
            noise = np.roll(base, i, axis=(0, 1))
            target = train_dir if i <= 800 else valid_dir
            cv2.imwrite(str(target / f"{i:04d}.png"), cv2.cvtColor(noise, cv2.COLOR_RGB2BGR))
        train, valid = discover_div2k_pngs(tmp)
        t0 = time.time()
        print(f"[div2k] fake DIV2K tree written to {tmp} in {time.time() - t0:.1f}s")
        return train, valid

    if use_kagglehub:
        if kagglehub is None:
            raise ColabPipelineError(
                "kagglehub is not installed - run `pip install kagglehub` or pass "
                "use_kagglehub=False and supply the official archives."
            )
        print(f"[div2k] kagglehub.dataset_download({KAGGLE_DATASET!r}) ...")
        try:
            source = Path(kagglehub.dataset_download(KAGGLE_DATASET))
        except Exception as exc:
            raise ColabPipelineError(f"kagglehub download failed: {exc}") from exc
        print(f"[div2k] downloaded to {source}")
    else:
        raw = Path(config.project_root) / "data" / "raw"
        if (raw / "div2k_hr").is_dir():
            source = raw / "div2k_hr"
        elif any(raw.rglob("*.png")):
            source = raw
        else:
            raise ColabPipelineError(
                "no DIV2K images found under data/raw (run scripts/setup_div2k.py "
                "locally first, or pass use_kagglehub=True)."
            )
    return discover_div2k_pngs(source)


def make_split(
    train_files: list[Path], valid_files: list[Path], *, mode: str, limits: dict[str, int | None]
) -> tuple[dict[str, list[str]], int]:
    """Deterministic, image-level-disjoint id-based split (a file in one split only).

    mode "700": train = 0001-0700 (official train head), validation = 0701-0800
                (official train tail), test = 0801-0900 (official valid). Same
                test set as the local project.
    mode "800": train = 0001-0800 (whole official train), validation = 0801-0850,
                test = 0851-0900 (both carved from the official valid set).
    """
    by_id = {_png_id(p): str(p) for p in train_files + valid_files}
    ids = sorted(by_id)
    if mode == "800":
        train = [i for i in ids if 1 <= i <= 800]
        validation = [i for i in ids if 801 <= i <= 850]
        test = [i for i in ids if 851 <= i <= 900]
    else:
        train = [i for i in ids if 1 <= i <= 700]
        validation = [i for i in ids if 701 <= i <= 800]
        test = [i for i in ids if 801 <= i <= 900]
    missing = (set(train) | set(validation) | set(test)) - set(ids)
    if missing:
        raise ColabPipelineError(f"split bands missing from the download: {sorted(missing)}")
    groups = {"train": train, "validation": validation, "test": test}
    kept = {}
    for name, band in groups.items():
        cap = limits.get(name)
        selected = band[:cap] if cap else band
        kept[name] = sorted(selected)
    return {name: [by_id[i] for i in band] for name, band in kept.items()}, len(by_id)


# ---------------------------------------------------------------------------
# Cache: run the ACTUAL embedder once per (image, payload) and keep windows
# ---------------------------------------------------------------------------


def synthesize_windows(
    bgr_u8: np.ndarray,
    payload: list[int],
    cfg: PipelineConfig,
) -> np.ndarray:
    """Watermark real pixels with the frozen embedder, then build per-bit
    15-value windows exactly as live inference will. Returns (bit_length, 15)."""
    rgb = cv2.cvtColor(bgr_u8, cv2.COLOR_BGR2RGB)
    result = embed(rgb, payload, cfg.embed_config())
    wm = result.watermarked_image
    if wm.shape[:2] != (cfg.image_size, cfg.image_size):
        wm = cv2.resize(wm, (cfg.image_size, cfg.image_size), interpolation=cv2.INTER_AREA)
    sigma = luminance_ll_singular_values(wm, cfg.model_config())
    return np.stack(
        [bit_window_singular_values(sigma, i, cfg.model_config()) for i in range(len(payload))]
    )  # (bit_length, window_size)


def _payload_for(index: int, cfg: PipelineConfig) -> list[int]:
    """A real registry-ID payload (codec + XOR mask) seeded by index - the exact
    physical bits the ownership flow embeds (labels = these bits)."""
    id_ = int(index) % id_registry.MAX_ENTRIES
    return id_registry.encode_id_bits(id_)


def cache_manifest(cfg: PipelineConfig) -> dict:
    return {
        "config_hash": cfg.config_hash(),
        "bit_length": cfg.bit_length,
        "window_size": cfg.window_size,
        "image_size": cfg.image_size,
        "alpha": cfg.alpha,
        "wavelet": "haar",
        "subband": "LL",
        "split_mode": cfg.split_mode,
        "payload_source": "id_registry.encode_id_bits(id) for id in [0,16)",
        "feature_transform": "per-window log1p -> standardise inside bit_window_singular_values",
        "embedder": "src.watermark.embed.embed (frozen Phase 6) - unmodified",
    }


def generate_cache(cfg: PipelineConfig, splits: dict[str, list[str]]) -> dict[str, Path]:
    """Stage A: for every (split, image) put the ACTUAL payload through the ACTUAL
    embedder and cache the (windows, labels) arrays. Writes train/validation/test
    npz + a clean-test npz (never-watermarked pixels, for the false-positive test)
    + normalization.npz + dataset_split.json + manifest. Rebuilds when the config
    hash changes; otherwise reuses an existing cache."""
    cache_root = Path(cfg.cache_dir)
    cache_root.mkdir(parents=True, exist_ok=True)
    manifest = cache_manifest(cfg)
    out: dict[str, Path] = {}

    (cache_root / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    split_paths = {}
    for split, files in splits.items():
        split_paths[split] = files
        print(f"[cache] {split}: {len(files)} images")

    for split, files in split_paths.items():
        npz = cache_root / f"{split}.npz"
        n = len(files)
        if npz.is_file():
            loaded = np.load(npz, allow_pickle=False)
            if int(loaded["windows"].shape[0]) == n * cfg.bit_length:
                print(f"[cache] reuse {npz.name} ({n * cfg.bit_length} windows)")
                out[split] = npz
                continue
        print(f"[cache] generating {split} ({n} images x {cfg.bit_length} bits) ...")
        t0 = time.time()
        all_windows: list[np.ndarray] = []
        all_labels: list[np.ndarray] = []
        for idx, path in enumerate(files):
            bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
            if bgr is None:
                raise ColabPipelineError(f"unreadable image {path}")
            payload = _payload_for(idx, cfg)
            windows = synthesize_windows(bgr, payload, cfg)
            all_windows.append(windows)
            all_labels.append(np.asarray(payload, dtype=np.float32))
            if (idx + 1) % 100 == 0:
                print(f"  ... {idx + 1}/{n} images ({time.time() - t0:.1f}s)")
        W = np.concatenate(all_windows).astype(np.float32)  # (n*bits, window_size)
        L = np.concatenate(all_labels).astype(np.float32)  # (n*bits,)
        img_ids = np.repeat(np.arange(n), cfg.bit_length).astype(np.int64)
        np.savez(npz, windows=W, labels=L, img_ids=img_ids)
        out[split] = npz
        _sanity_checks(W, L, cfg, split)
        print(f"[cache] wrote {npz.name} [{W.shape}] in {time.time() - t0:.1f}s")

    # Clean (never-watermarked) test windows for the false-positive test.
    clean_npz = cache_root / "clean_test.npz"
    if not clean_npz.is_file():  # keep deterministic
        files = split_paths["test"]
        W, L0 = [], []
        for idx, path in enumerate(files):
            bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
            rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
            if rgb.shape[:2] != (cfg.image_size, cfg.image_size):
                rgb = cv2.resize(
                    rgb, (cfg.image_size, cfg.image_size), interpolation=cv2.INTER_AREA
                )
            sigma = luminance_ll_singular_values(rgb, cfg.model_config())
            windows = np.stack(
                [
                    bit_window_singular_values(sigma, i, cfg.model_config())
                    for i in range(cfg.bit_length)
                ]
            )
            W.append(windows)
            L0.append(np.full(cfg.bit_length, np.nan, dtype=np.float32))  # no label
        C = np.concatenate(W).astype(np.float32)
        np.savez(
            clean_npz,
            windows=C,
            img_ids=np.repeat(np.arange(len(files)), cfg.bit_length).astype(np.int64),
            labels=np.concatenate(L0),
        )
        print(f"[cache] wrote {clean_npz.name} [{C.shape}] (clean, no watermark)")
    out["clean_test"] = clean_npz

    _write_normalization(cfg, out)
    return out


def _sanity_checks(W: np.ndarray, L: np.ndarray, cfg: PipelineConfig, split: str) -> None:
    if W.ndim != 2 or W.shape[1] != cfg.window_size:
        raise ColabPipelineError(
            f"{split}: window shape {W.shape}; expected (_, {cfg.window_size})"
        )
    if W.shape[0] != L.shape[0]:
        raise ColabPipelineError(f"{split}: {W.shape[0]} windows vs {L.shape[0]} labels mismatch")
    if not np.isfinite(W).all():
        raise ColabPipelineError(f"{split}: non-finite window values")
    if not np.isfinite(L).all():
        raise ColabPipelineError(f"{split}: non-finite labels")
    frac1 = float(L.mean())
    zeros = int((L == 0).sum())
    print(
        f"[sanity] {split}: finite={np.isfinite(W).all()} n={W.shape[0]} "
        f"label0={zeros} label1={W.shape[0] - zeros} frac1={frac1:.3f}"
    )


def _write_normalization(cfg: PipelineConfig, out: dict[str, Path]) -> None:
    """Record the feature transform the decoder expects.

    The model's input transform is the per-window ``log1p`` -> standardise that
    lives in ``bit_window_singular_values`` (identical at training and
    inference - this is the authoritative normalization, applied before the
    network and never recomputed from a single image). Global train-set stats
    are saved alongside for diagnostics / future feature engineering."""
    cache_root = Path(cfg.cache_dir)
    paths = (out.get("train"), out.get("validation"))
    means, stds, n = [], [], []
    for p in paths:
        if p and Path(p).is_file():
            a = np.load(p, allow_pickle=False)["windows"]
            means.append(a.mean(axis=0))
            stds.append(a.std(axis=0))
            n.append(len(a))
    if n:
        counts = np.asarray(n, dtype=np.float64)
        global_mean = np.average(np.asarray(means, dtype=np.float64), axis=0, weights=counts)
        # pooled std across splits (full-sample estimator for diagnostics only)
        var_part = (
            np.asarray(stds, dtype=np.float64) ** 2 + np.asarray(means, dtype=np.float64) ** 2
        ) * counts[:, None]
        pooled_std = np.sqrt(var_part.sum(axis=0) / counts.sum() - global_mean**2)
    else:
        global_mean = np.zeros(cfg.window_size)
        pooled_std = np.zeros(cfg.window_size)
    np.savez(
        cache_root / "normalization.npz",
        bit_length=cfg.bit_length,
        window_size=cfg.window_size,
        transform="per_window_log1p_standardised_inside_bit_window_singular_values",
        transform_applied_before_model=True,
        global_train_mean=global_mean.astype(np.float32),
        global_train_std=pooled_std.astype(np.float32),
    )
    print("[cache] normalization.npz written (per-window transform is authoritative)")


# ---------------------------------------------------------------------------
# Data loaders from cache
# ---------------------------------------------------------------------------


class WindowArrayDataset(torch.utils.data.Dataset):
    def __init__(self, npz: Path):
        data = np.load(str(npz), allow_pickle=False)
        self.windows = torch.from_numpy(data["windows"].astype(np.float32))
        self.labels = torch.from_numpy(data["labels"].astype(np.float32))
        self.img_ids = torch.from_numpy(data["img_ids"].astype(np.int64))

    def __len__(self) -> int:
        return len(self.windows)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor, int]:
        return self.windows[idx], self.labels[idx], int(self.img_ids[idx])


def build_loaders(cfg: PipelineConfig, cache: dict[str, Path], *, shuffle_train: bool = True):
    train = torch.utils.data.DataLoader(
        WindowArrayDataset(cache["train"]),
        batch_size=cfg.batch_size,
        shuffle=shuffle_train,
        num_workers=cfg.num_workers,
    )
    val = torch.utils.data.DataLoader(
        WindowArrayDataset(cache["validation"]),
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
    )
    test = torch.utils.data.DataLoader(
        WindowArrayDataset(cache["test"]),
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
    )
    return train, val, test


# ---------------------------------------------------------------------------
# Training (Stage B)
# ---------------------------------------------------------------------------


def _binary_metrics(logits: torch.Tensor, targets: torch.Tensor) -> dict:
    preds = (torch.sigmoid(logits) > 0.5).float()
    ok = preds.eq(targets)
    n = targets.numel()
    acc = float(ok.sum().item()) / max(n, 1)
    ber = 1.0 - acc
    # confusion (flat: tn,fp,fn,tp counts)
    tp = int(((preds == 1) & (targets == 1)).sum().item())
    tn = int(((preds == 0) & (targets == 0)).sum().item())
    fp = int(((preds == 1) & (targets == 0)).sum().item())
    fn = int(((preds == 0) & (targets == 1)).sum().item())
    precision = tp / max(tp + fp, 1)
    recall = tp / max(tp + fn, 1)
    f1 = 2 * precision * recall / max(precision + recall, 1e-9)
    return {
        "bit_accuracy": acc,
        "ber": ber,
        "tn": tn,
        "fp": fp,
        "fn": fn,
        "tp": tp,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "n_bits": n,
    }


def _evaluate_arrays(model: nn.Module, loader, device: str) -> dict:
    model.eval()
    loss = nn.BCEWithLogitsLoss()
    tot, n = 0.0, 0
    with torch.no_grad():
        for windows, labels, _ in loader:
            windows = windows.to(device)
            labels = labels.to(device)
            logits = model(windows).squeeze(1)
            tot += loss(logits, labels).item() * len(windows)
            n += len(windows)
    return {"loss": tot / max(n, 1)}


def _train_epoch(model, loader, loss_fn, optimizer, cfg, device) -> dict:
    model.train()
    running, bits, correct = 0.0, 0, 0
    for windows, labels, _ in loader:
        windows, labels = windows.to(device), labels.to(device)
        optimizer.zero_grad(set_to_none=True)
        logits = model(windows).squeeze(1)
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()
        running += loss.item() * len(windows)
        bits += labels.numel()
        correct += int((torch.sigmoid(logits.detach()) > 0.5).float().eq(labels).sum().item())
    return {"train_loss": running / max(bits, 1), "train_bit_acc": correct / max(bits, 1)}


def train_model(
    cfg: PipelineConfig,
    cache: dict[str, Path],
    *,
    device: str = "auto",
    resume: str | None = None,
) -> dict[str, object]:
    """Stage B: train the windowed CNN on the cached windows. Saves best+last
    checkpoints, history csv and training_config.json. Auto-resumes from an
    existing best checkpoint if present and ``resume`` is not given."""
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")
    _seed_everything(cfg.seed)

    out_dir = Path(cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    best_path = out_dir / "windowed_cnn_best.pt"
    last_path = out_dir / "windowed_cnn_last.pt"
    history_path = out_dir / "training_history.csv"

    model = WindowedCNNExtractor(cfg.model_config()).to(device)
    start_epoch, best_bit_acc, best_epoch = 0, -1.0, -1

    train_loader, val_loader, _ = build_loaders(cfg, cache)

    if resume:
        if not Path(resume).is_file():
            raise ColabPipelineError(f"--resume checkpoint not found: {resume}")
        model, meta = load_windowed_checkpoint(resume, map_location=device)
        model = model.to(device)
        start_epoch = int(meta.get("epoch", 0)) + 1
        best_bit_acc = float(meta.get("best_val_bit_acc", -1.0))
        best_epoch = int(meta.get("best_epoch", -1))
        print(
            f"[train] resuming from {resume} at epoch {start_epoch} "
            f"(prior best val_bit_acc={best_bit_acc:.4f} at epoch {best_epoch})"
        )
    elif best_path.is_file():
        model, meta = load_windowed_checkpoint(str(best_path), map_location=device)
        model = model.to(device)
        start_epoch = int(meta.get("epoch", 0)) + 1
        best_bit_acc = float(meta.get("best_val_bit_acc", -1.0))
        best_epoch = int(meta.get("best_epoch", -1))
        print(
            f"[train] existing best checkpoint found -> resuming at epoch {start_epoch} "
            f"(use --resume to override). best val_bit_acc={best_bit_acc:.4f}"
        )

    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr)
    params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(
        f"[train] device={device} params={params:,} bits={cfg.bit_length} "
        f"window={cfg.window_size} alpha={cfg.alpha} epochs={start_epoch}..{cfg.epochs}"
    )

    common_extra = {
        "bit_length": cfg.bit_length,
        "window_size": cfg.window_size,
        "image_size": cfg.image_size,
        "train_config": asdict(cfg),
    }
    rows: list[dict] = []
    no_improve = 0
    early_stopped = False

    def _val_metrics() -> dict:
        model.eval()
        vl, tot_loss, n = [], 0.0, 0
        with torch.no_grad():
            for w, l, _ in val_loader:
                logits = model(w.to(device)).squeeze(1)
                vl.append((logits.cpu(), l))
                tot_loss += nn.functional.binary_cross_entropy_with_logits(
                    logits, l.to(device)
                ).item() * len(w)
                n += len(w)
        logits = torch.cat([x for x, _ in vl], dim=0)
        labels = torch.cat([y for _, y in vl], dim=0)
        metrics = _binary_metrics(logits, labels)
        metrics["loss"] = tot_loss / max(n, 1)
        return metrics

    if best_bit_acc < 0:
        print(f"[train] epoch 0 (init) val_loss={_val_metrics()['loss']:.4f}")

    for epoch in range(start_epoch, cfg.epochs + 1):
        t0 = time.time()
        tr = _train_epoch(model, train_loader, loss_fn, optimizer, cfg, device)
        vm = _val_metrics()
        row = {
            "epoch": epoch,
            **{k: round(v, 6) if isinstance(v, float) else v for k, v in tr.items()},
            "val_loss": round(vm["loss"], 6),
            **{
                f"val_{k}": (round(v, 6) if isinstance(v, float) else v)
                for k, v in vm.items()
                if k != "n_bits"
            },
        }
        rows.append(row)
        improved = not best_path.is_file() or vm["bit_accuracy"] > best_bit_acc + 1e-6
        if improved:
            best_bit_acc, best_epoch = vm["bit_accuracy"], epoch
            no_improve = 0
            save_windowed_checkpoint(
                str(best_path),
                model,
                extra={
                    **common_extra,
                    "epoch": epoch,
                    "val_metrics": vm,
                    "best_val_bit_acc": best_bit_acc,
                    "best_epoch": best_epoch,
                },
            )
            print(
                f"[train] epoch {epoch:2d} val_bit_acc={vm['bit_accuracy']:.4f} "
                f"ber={vm['ber']:.4f} f1={vm['f1']:.4f} ({time.time() - t0:.1f}s)  *BEST*"
            )
        else:
            no_improve += 1
            print(
                f"[train] epoch {epoch:2d} val_bit_acc={vm['bit_accuracy']:.4f} "
                f"ber={vm['ber']:.4f} f1={vm['f1']:.4f} ({time.time() - t0:.1f}s)"
            )
            if no_improve >= cfg.patience:
                early_stopped = True
                print(f"[train] early stopping after {epoch} epochs (patience {cfg.patience})")
                break
        save_windowed_checkpoint(
            str(last_path),
            model,
            extra={
                **common_extra,
                "epoch": epoch,
                "val_metrics": vm,
                "best_val_bit_acc": best_bit_acc,
                "best_epoch": best_epoch,
            },
        )

    with history_path.open("w", newline="", encoding="utf-8") as fh:
        if rows:
            w = csv.DictWriter(fh, fieldnames=list(rows[0]))
            w.writeheader()
            w.writerows(rows)

    training_config = {
        "epochs": cfg.epochs,
        "batch_size": cfg.batch_size,
        "lr": cfg.lr,
        "patience": cfg.patience,
        "seed": cfg.seed,
        "device": device,
        "bit_length": cfg.bit_length,
        "window_size": cfg.window_size,
        "image_size": cfg.image_size,
        "alpha": cfg.alpha,
        "model": "WindowedCNNExtractor (Conv1d 32/64, k=3, flatten, Dense 64, Dense 1)",
        "split_mode": cfg.split_mode,
        "best_epoch": best_epoch,
        "best_val_bit_acc": best_bit_acc,
    }
    (out_dir / "training_config.json").write_text(
        json.dumps(training_config, indent=2), encoding="utf-8"
    )
    if rows:
        (out_dir / "training_config.json").write_text(
            json.dumps({**training_config, "final_row": rows[-1]}, indent=2), encoding="utf-8"
        )

    return {
        "model": model,
        "best_path": str(best_path),
        "last_path": str(last_path),
        "history_path": str(history_path),
        "best_epoch": best_epoch,
        "best_val_bit_acc": best_bit_acc,
        "early_stopped": early_stopped,
        "rows": rows,
    }


# ---------------------------------------------------------------------------
# Evaluation (Stage C)
# ---------------------------------------------------------------------------


def _predict_bits(
    model: nn.Module, loader, device: str
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    model.eval()
    probs, labels, img_ids = [], [], []
    with torch.no_grad():
        for windows, lbl, img in loader:
            p = torch.sigmoid(model(windows.to(device)).squeeze(1)).cpu().numpy()
            probs.append(p)
            labels.append(lbl.numpy())
            img_ids.append(img.numpy())
    return (np.concatenate(probs), np.concatenate(labels), np.concatenate(img_ids))


def predict_windows(model: nn.Module, windows: np.ndarray, device: str) -> np.ndarray:
    model.eval()
    out = []
    with torch.no_grad():
        for i in range(0, len(windows), 256):
            chunk = torch.from_numpy(windows[i : i + 256]).float().to(device)
            out.append(torch.sigmoid(model(chunk).squeeze(1)).cpu().numpy())
    return np.concatenate(out)


def evaluate_model(
    cfg: PipelineConfig,
    cache: dict[str, Path],
    trained,
    *,
    device: str = "auto",
    threshold: float = 0.78,
) -> dict:
    """Stage C: honest test-set numbers - bit level, full registry-ID recovery,
    controlled false-positive rate, and a clean-image sanity confirmation."""
    if device == "auto":
        device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")
    model = trained["model"]

    _, _, test_loader = build_loaders(cfg, cache)
    probs_test, labels_test, img_ids_test = _predict_bits(model, test_loader, device)
    bit_metrics = _binary_metrics(
        torch.from_numpy((probs_test > 0.5).astype(np.float32)),
        torch.from_numpy(labels_test.astype(np.float32)),
    )
    print(f"[eval] test bit-level: {bit_metrics}")

    # Full-payload registry-ID recovery (decode via the real codec).
    recovered = []
    n_ids_ok = n_registered = 0
    for img_id in np.unique(img_ids_test):
        mask = img_ids_test == img_id
        pred_bits = (probs_test[mask] > 0.5).astype(int).tolist()
        true_bits = labels_test[mask].astype(int).tolist()
        true_id, _, _ = id_registry.decode_id_bits(true_bits)
        try:
            pred_id, mean_conf, min_conf = id_registry.decode_id_bits(pred_bits)
            valid = True
        except ValueError:
            pred_id, mean_conf, min_conf, valid = -1, 0.0, 0.0, False
        exact = valid and pred_id == true_id
        n_ids_ok += int(exact)
        n_registered += int(valid and min_conf >= threshold)
        recovered.append(
            {
                "image_id": int(img_id),
                "true_id": int(true_id),
                "pred_id": int(pred_id),
                "exact": exact,
                "valid": valid,
                "mean_conf": float(mean_conf),
                "min_conf": float(min_conf),
                "ber": float(1.0 - float(np.mean(mask & (pred_bits == true_bits)))),
            }
        )
    full_payload = {
        "test_images": len(recovered),
        "exact_id": n_ids_ok,
        "exact_id_rate": n_ids_ok / max(len(recovered), 1),
        "registered_at_threshold": n_registered,
        "registered_rate": n_registered / max(len(recovered), 1),
        "threshold_used": threshold,
        "mean_min_conf": float(np.mean([r["min_conf"] for r in recovered])),
        "per_image": recovered,
    }
    print(
        f"[eval] full-payload ID recovery: exact={n_ids_ok}/{len(recovered)} "
        f"registered={n_registered}/{len(recovered)} @ threshold {threshold}"
    )

    # Controlled test on image files currently in the repo - skip in smoke runs.
    return {
        "bit_level": bit_metrics,
        "full_payload": full_payload,
        "false_positives": _false_positive_test(cfg, cache, model, device, threshold),
        "robustness": _robustness_mini(cfg, cache, model, device, n=8),
        "data_quality": None,
    }


def _false_positive_test(
    cfg: PipelineConfig, cache: dict[str, Path], model, device: str, threshold: float
) -> dict:
    """Feed the decoder **clean, never-watermarked** test pixels. A registered
    ID at >= threshold is a false positive (spurious ownership match)."""
    clean_npz = cache.get("clean_test")
    loader = torch.utils.data.DataLoader(
        WindowArrayDataset(clean_npz), batch_size=cfg.batch_size, shuffle=False
    )
    probs, _, img_ids = _predict_bits(model, loader, device)
    fps = 0
    hits = []
    for img_id in np.unique(img_ids):
        mask = img_ids == img_id
        bits = (probs[mask] > 0.5).astype(int).tolist()
        try:
            pred_id, _, min_conf = id_registry.decode_id_bits(bits)
            registered = min_conf >= threshold
        except ValueError:
            pred_id, min_conf, registered = -1, 0.0, False
        if registered:
            fps += 1
            hits.append(
                {"image_id": int(img_id), "pred_id": int(pred_id), "min_conf": float(min_conf)}
            )
    n = img_ids.max() - img_ids.min() + 1 if len(img_ids) else 0
    result = {
        "clean_test_images": len(np.unique(img_ids)),
        "false_positive_registrations": fps,
        "false_positive_rate": fps / max(len(np.unique(img_ids)), 1),
        "threshold_used": threshold,
        "hits": hits,
    }
    print(f"[eval] false positives on clean images: {fps}/{n} @ threshold {threshold}")
    return result


def _robustness_mini(
    cfg: PipelineConfig, cache: dict[str, Path], model, device: str, n: int = 8
) -> dict:
    """Image-level re-embed smoke: embed real payloads into clean test images,
    apply common post-processing (PNG re-encode, JPEG q90, mild blur), then
    blind-decode - reports BER. Uses the same authoritative feature mapping."""
    clean_npz = cache.get("clean_test")
    if clean_npz is None:
        return {}
    # rebuild clean test images from the split manifest when available
    split_json = Path(cfg.out_dir) / "dataset_split.json"
    if not split_json.is_file():
        return {"skipped": "dataset_split.json missing"}
    split_data = json.loads(split_json.read_text(encoding="utf-8"))
    files = (split_data.get("all_files") or {}).get("test", []) or split_data.get("test", [])
    if not files or not Path(files[0]).is_file():
        return {"skipped": "test image files unavailable on this machine"}

    results = []
    for idx, path in enumerate(files[:n]):
        payload = _payload_for(idx, cfg)
        bgr = cv2.imread(path, cv2.IMREAD_COLOR)
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
        if rgb.shape[:2] != (cfg.image_size, cfg.image_size):
            rgb = cv2.resize(rgb, (cfg.image_size, cfg.image_size), interpolation=cv2.INTER_AREA)
        wm = embed(rgb, payload, cfg.embed_config()).watermarked_image
        variants = {"png_reencode": None, "jpeg_q90": None, "blur_k3": None}
        wm_bgr = cv2.cvtColor(wm, cv2.COLOR_RGB2BGR)
        _ok, buf = cv2.imencode(".png", wm_bgr)
        variants["png_reencode"] = cv2.imdecode(buf, cv2.IMREAD_COLOR)
        __, buf = cv2.imencode(".jpg", wm_bgr, [cv2.IMWRITE_JPEG_QUALITY, 90])
        variants["jpeg_q90"] = cv2.imdecode(buf, cv2.IMREAD_COLOR)
        variants["blur_k3"] = cv2.GaussianBlur(wm_bgr, (3, 3), 0)

        per = {}
        for name, arr in variants.items():
            arr_rgb = cv2.cvtColor(arr, cv2.COLOR_BGR2RGB)
            sigma = luminance_ll_singular_values(arr_rgb, cfg.model_config())
            windows = np.stack(
                [
                    bit_window_singular_values(sigma, i, cfg.model_config())
                    for i in range(cfg.bit_length)
                ]
            )
            probs = predict_windows(model, windows, device)
            bits = (probs > 0.5).astype(int)
            ber = float(np.mean(bits != np.asarray(payload)))
            per[name] = {"bit_acc": 1.0 - ber, "ber": ber}
        results.append({"image_id": idx, "variants": per})
    return {"images": results}


def write_metrics(cfg: PipelineConfig, trained: dict, eval_results: dict) -> str:
    metrics = {
        "model": "WindowedCNNExtractor",
        "bit_length": cfg.bit_length,
        "window_size": cfg.window_size,
        "image_size": cfg.image_size,
        "alpha": cfg.alpha,
        "split_mode": cfg.split_mode,
        "best_epoch": trained["best_epoch"],
        "best_val_bit_acc": trained["best_val_bit_acc"],
        "early_stopped": trained["early_stopped"],
        "test_bit_level": eval_results["bit_level"],
        "full_payload": eval_results["full_payload"],
        "false_positives": eval_results["false_positives"],
        "robustness": eval_results["robustness"],
        "as_of": time.strftime("%Y-%m-%d %H:%M:%S"),
    }
    path = Path(cfg.out_dir) / "metrics.json"
    path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"[eval] metrics.json written ({path})")
    return str(path)


# ---------------------------------------------------------------------------
# Packaging (Stage D)
# ---------------------------------------------------------------------------


def write_dataset_split_json(cfg: PipelineConfig, splits: dict[str, list[str]]) -> str:
    out_dir = Path(cfg.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = {
        "split_mode": cfg.split_mode,
        "note": (
            "Data returns: train/validation/test IDs. DIV2K releases 800 "
            "train + 100 valid images; '800/100/100' from the original task "
            "brief needs 1000 images, so the model uses the project's 700/100/100: "
            "train=0001-0700, validation=0701-0800, test=0801-0900 (official "
            "valid set, same test the local project uses)."
        ),
        "splits": {
            name: {
                "count": len(files),
                "first": files[0] if files else None,
                "last": files[-1] if files else None,
            }
            for name, files in splits.items()
        },
        "all_files": {name: files for name, files in splits.items()},
    }
    path = out_dir / "dataset_split.json"
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"[split] dataset_split.json written ({path})")
    return str(path)


def package_artifacts(cfg: PipelineConfig, *, device: str = "cpu") -> str:
    """Build the self-contained windowed_cnn_model_package.zip: checkpoint(s),
    normalization, decoder config (model + bit_length + image_size), training
    config, split, metrics, history."""
    out_dir = Path(cfg.out_dir)
    import zipfile

    decoder_config = {
        "decoder_class": "WindowedCNNExtractor",
        "bit_length": cfg.bit_length,
        "window_size": cfg.window_size,
        "image_size": cfg.image_size,
        "alpha": cfg.alpha,
        "wavelet": "haar",
        "subband": "LL",
        "input_transform": "per_window_log1p_standardised_inside_bit_window_singular_values",
        "reliability_threshold": 0.78,
    }

    zip_path = out_dir / "windowed_cnn_model_package.zip"
    # normalization.npz is produced by the cache stage (cache_dir), not the
    # training stage - normalise its location so the package is self-contained.
    norm_src = out_dir / "normalization.npz"
    if not norm_src.is_file():
        cache_norm = Path(cfg.cache_dir) / "normalization.npz"
        if cache_norm.is_file():
            import shutil

            shutil.copy2(cache_norm, norm_src)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        wm_names = ["windowed_cnn_best.pt", "windowed_cnn_last.pt"]
        for name in wm_names:
            p = out_dir / name
            if p.is_file():
                zf.write(p, name)
        href = out_dir / "decoder_config.json"
        href.write_text(json.dumps(decoder_config, indent=2), encoding="utf-8")
        for name in [
            "decoder_config.json",
            "normalization.npz",
            "training_config.json",
            "dataset_split.json",
            "metrics.json",
            "training_history.csv",
        ]:
            p = out_dir / name
            if p.is_file():
                zf.write(p, name)
    print(f"[package] {zip_path} ({zip_path.stat().st_size / 1e6:.2f} MB)")
    return str(zip_path)


def load_checkpoints_into_repo(cfg: PipelineConfig) -> str:
    """Copy packaged artifacts into the project's models/experimental/windowed_cnn
    directory (the local app's decoder_loader looks here)."""
    import shutil

    dest = (Path(cfg.project_root) / "models" / "experimental" / "windowed_cnn").resolve()
    dest.mkdir(parents=True, exist_ok=True)
    moved = []
    for name in [
        "windowed_cnn_best.pt",
        "windowed_cnn_last.pt",
        "decoder_config.json",
        "normalization.npz",
        "training_config.json",
        "dataset_split.json",
        "metrics.json",
        "training_history.csv",
    ]:
        src = Path(cfg.out_dir) / name
        if src.is_file():
            shutil.copy2(src, dest / name)
            moved.append(str(dest / name))
    print(f"[repo] artifacts copied into the local project: {moved}")
    return str(dest)


# ---------------------------------------------------------------------------
# CLI orchestration
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=str(_PROJECT_ROOT))
    parser.add_argument("--all", action="store_true", help="run the entire pipeline end-to-end")
    parser.add_argument(
        "--smoke",
        action="store_true",
        help="tiny train/val/test caps + 1 epoch to verify the pipeline",
    )
    parser.add_argument("--epochs", type=int)
    parser.add_argument("--split-mode", choices=["700", "800"])
    parser.add_argument(
        "--fake",
        action="store_true",
        help="dev-only: synthesize a small DIV2K-shaped tree and run on it",
    )
    parser.add_argument("--require-gpu", action="store_true")
    parser.add_argument("--resume")
    parser.add_argument("--out-dir", default="content/out")
    parser.add_argument("--cache-dir", default="content/windows")
    parser.add_argument(
        "--processed",
        action="store_true",
        help="use the local data/processed/<root> split dirs (train/validation/test) "
        "instead of downloading DIV2K",
    )
    args = parser.parse_args(argv)

    cfg = load_pipeline_config(
        args.project_root,
        {
            "epochs": args.epochs,
            "split_mode": args.split_mode,
            "out_dir": args.out_dir,
            "cache_dir": args.cache_dir,
            "train_images": (8 if args.smoke else None),
            "val_images": (4 if args.smoke else None),
            "test_images": (4 if args.smoke else None),
        },
    ).resolved()

    print(f"[env] {check_environment(require_gpu=args.require_gpu)}")
    if args.processed:
        processed = Path(cfg.processed_root)
        train_files = sorted(
            list((processed / cfg.train_split).glob("*.png"))
            + list((processed / cfg.validation_split).glob("*.png"))
        )
        valid_files = sorted((processed / cfg.test_split).glob("*.png"))
        if not train_files or not valid_files:
            raise ColabPipelineError(
                f"--processed: no images under {processed} - run scripts/setup_div2k.py first"
            )
    else:
        train_files, valid_files = download_div2k(cfg, use_kagglehub=not args.smoke, fake=args.fake)
    splits, total = make_split(
        train_files,
        valid_files,
        mode=cfg.split_mode,
        limits={"train": cfg.train_images, "validation": cfg.val_images, "test": cfg.test_images},
    )
    for name, files in splits.items():
        print(f"  split {name}: {len(files)} images")
    if args.smoke:
        print(f"[smoke] using {total} total files, split {cfg.split_mode}")
    write_dataset_split_json(cfg, splits)

    cache = generate_cache(cfg, splits)
    print(f"[cache] manifest hash: {cfg.config_hash()}")

    trained = train_model(cfg, cache, resume=args.resume)
    energy = evaluate_model(cfg, cache, trained)
    write_metrics(cfg, trained, energy)
    package_artifacts(cfg)
    load_checkpoints_into_repo(cfg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
