"""Package the project source + configs + training script into a single zip
that can be uploaded to Google Colab (or dropped into any GPU box).

    python scripts/build_colab_payload.py -o /tmp/deep_watermarking_colab.zip

The zip contains everything the notebook needs:
    src/            the actual project source (embedder, codec, windowed model)
    configs/windowed_cnn.yaml
    training/colab_train_decoder.py      THE pipeline
    COLLAB_README.md                     canary + integrity hint
    VERSION.txt                          payload build stamp
"""

from __future__ import annotations

import argparse
import datetime
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _iter_project_files() -> list[tuple[Path, str]]:
    files: list[tuple[Path, str]] = []

    def add(rel: str) -> None:
        p = ROOT / rel
        if p.is_file():
            files.append((p, rel))

    # Deterministic order (config first for readability).
    add("configs/windowed_cnn.yaml")
    add("training/colab_train_decoder.py")

    for py in sorted((ROOT / "src").rglob("*.py")):
        if "__pycache__" in py.parts:
            continue
        files.append((py, str(py.relative_to(ROOT))))

    for yml in sorted((ROOT / "src").rglob("*.yaml")):
        if "__pycache__" in yml.parts:
            continue
        files.append((yml, str(yml.relative_to(ROOT))))

    return files


def build(output: Path, *, include_venv_note: bool = True) -> Path:
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    stamp = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")
    canary = (
        "Project ZIP for training/colab_windowed_cnn_training.ipynb\n"
        f"built {stamp}\n"
        "\n"
        "This payload carries the ACTUAL project encoder (src/watermark/embed.py),\n"
        "the registry codec (src/watermark/id_registry.py) and the windowed CNN -\n"
        "training data in the notebook is generated by these, never re-implemented.\n"
    ).encode() + (b"\n(staged; the notebook panics if this file is missing)\n")

    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("COLLAB_README.md", canary)
        zf.writestr("VERSION.txt", stamp)
        n_py = 0
        for src, arcname in _iter_project_files():
            zf.write(src, arcname)
            if arcname.endswith(".py"):
                n_py += 1
        # Uncompressed? No - default compressed; report sizes.
    size_mb = output.stat().st_size / 1e6
    print(
        f"[build] {output} ({size_mb:.2f} MB, {n_py} .py files) -> upload to Colab "
        f"and unzip under /content/deep-watermarking"
    )
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", default=str(ROOT / "colab_payload.zip"))
    args = parser.parse_args(argv)
    build(Path(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
